[package]
name = "economy-core"
version = "2.0.0"
edition = "2021"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
tokio = { version = "1", features = ["full", "signal"] }
tower-http = { version = "0.6", features = ["fs", "cors", "timeout"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
bincode = { version = "2.0.0-rc.3", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.9"
rand_distr = "0.5"
parking_lot = "0.12"
reqwest = { version = "0.13", features = ["json"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
rustc-hash = "2.1.0"
thiserror = "1.0"
aws-lc-rs = { version = "1.11.1", features = ["bindgen"] }

[env]
# 1. MinGW 标准库路径
# 2. GCC 内部头文件路径 (w64devkit 通常在此目录下)
# 3. LLVM 自身资源路径 (你之前找到的那个)
BINDGEN_EXTRA_CLANG_ARGS = """
-I D:/Downloader/downloads/w64devkit/x86_64-w64-mingw32/include 
-I D:/Downloader/downloads/w64devkit/lib/gcc/x86_64-w64-mingw32/14.2.0/include 
-I D:/Program Files/LLVM/lib/clang/21/include
"""