[package]
name = "economy-core"
version = "2.0.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
tokio = { version = "1", features = ["full", "signal"] }
tower-http = { version = "0.6", features = ["fs", "cors", "timeout"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
bincode = { version = "2.0.0-rc.3", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.9"
rand_distr = "0.5"
rustc-hash = "2.1.0"
parking_lot = "0.12"
thiserror = "1.0"
validator = { version = "0.19", features = ["derive"] }
futures = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

# 核心修复点
reqwest = { version = "0.13", features = ["json", "rustls-tls-native-roots"] }
aws-lc-rs = { version = "1.11", features = ["bindgen", "rustls"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
